import { MediaMetadata, FormatsResponse, DownloadProgressInfo, DownloadStatus } from '../types';
export interface InitDownloadParams { formatId:string;fileName?:string;customTitle?:string;url?:string;mediaId?:string;durationSeconds?:number;thumbnail?:string;type?:string;previewUrl?:string; }
export interface InitDownloadResponse { success:boolean;downloadId:string;fileName:string;ext:string;formatLabel:string;mediaType:'video'|'audio'|'image';totalBytes:number;fileSizeStr:string;contentType:string;fileUrl:string;progressUrl:string; }
export class ApiService{
 static async getMetadata(url:string):Promise<MediaMetadata>{const r=await fetch('/api/metadata',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Unable to read media.');return d.data;}
 static async getFormats(durationSeconds=180,availableQualities:string[]=[],url?:string):Promise<FormatsResponse>{const r=await fetch('/api/formats',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({durationSeconds,qualities:availableQualities,url})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Failed to retrieve formats.');return{audioFormats:d.audioFormats||[],videoFormats:d.videoFormats||[],imageFormats:d.imageFormats||[]};}
 static async initDownload(p:InitDownloadParams):Promise<InitDownloadResponse>{const r=await fetch('/api/download',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Download failed.');return d;}
 static async getProgress(id:string):Promise<DownloadProgressInfo>{const r=await fetch(`/api/download/${encodeURIComponent(id)}/progress`);const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Progress unavailable.');return{downloadId:d.downloadId,status:d.status,percent:d.percent,downloadedBytes:d.downloadedBytes,totalBytes:d.totalBytes,speed:d.speed,fileName:d.fileName,formatLabel:d.formatLabel,ext:d.ext,type:d.mediaType,thumbnail:d.thumbnail,errorMessage:d.errorMessage};}
 static async cancelDownload(id:string){try{return(await fetch(`/api/download/${encodeURIComponent(id)}/cancel`,{method:'POST'})).ok}catch{return false}}
 static async downloadFileStream(id:string,signal?:AbortSignal,onProgress?:(x:{percent:number;downloadedBytes:number;totalBytes:number;speed:string;status:DownloadStatus})=>void){const r=await fetch(`/api/download/${encodeURIComponent(id)}/file`,{signal});if(!r.ok)throw new Error('Failed to retrieve media file.');const ct=r.headers.get('Content-Type')||'video/mp4',total=parseInt(r.headers.get('Content-Length')||'0',10);if(!r.body){const b=await r.blob();onProgress?.({percent:100,downloadedBytes:b.size,totalBytes:total||b.size,speed:'0 B/s',status:'completed'});return{blob:b,contentType:ct}}const rd=r.body.getReader(),chunks:Uint8Array[]=[];let got=0,last=performance.now(),lastB=0,sp='0 B/s';for(;;){if(signal?.aborted)throw new Error('DOWNLOAD_CANCELLED');const{x,done}=await rd.read().then(v=>({x:v.value,done:v.done}));if(done)break;if(x){chunks.push(x);got+=x.length;const now=performance.now(),dt=(now-last)/1000;if(dt>=.25){sp=this.formatSpeed((got-lastB)/dt);last=now;lastB=got}const pct=total?Math.min(100,Math.round(got/total*100)):-1;onProgress?.({percent:pct,downloadedBytes:got,totalBytes:total,speed:sp,status:pct>=100?'converting':'downloading'})}}const b=new Blob(chunks,{type:ct});onProgress?.({percent:100,downloadedBytes:b.size,totalBytes:total||b.size,speed:sp,status:'completed'});return{blob:b,contentType:ct}}
 static formatSpeed(b:number){if(b<=0||!isFinite(b))return'0 B/s';if(b<1024)return`${Math.round(b)} B/s`;if(b<1048576)return`${(b/1024).toFixed(1)} KB/s`;if(b<1073741824)return`${(b/1048576).toFixed(1)} MB/s`;return`${(b/1073741824).toFixed(2)} GB/s`}
 static formatBytes(b:number){if(b<=0||!isFinite(b))return'0 MB';if(b<1024)return`${b} B`;if(b<1048576)return`${(b/1024).toFixed(1)} KB`;if(b<1073741824)return`${(b/1048576).toFixed(1)} MB`;return`${(b/1073741824).toFixed(2)} GB`}
 static async grab(url:string){try{return await(await fetch('/api/grab',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})})).json()}catch{return{downloadable:false,message:'No downloadable media detected.'}}}
 static async getYouTubeSuggestions(q:string):Promise<string[]>{try{return(await(await fetch(`/api/youtube/suggestions?q=${encodeURIComponent(q)}`)).json()).suggestions||[]}catch{return[]}}
 static async getYouTubeSearchFromPublicApi(q:string):Promise<any[]>{if(!q.trim())return[];const ps=[['https://pipedapi.kavin.rocks','p'],['https://pipedapi.leptons.xyz','p'],['https://pipedapi.nosebs.ru','p'],['https://pipedapi.adminforge.de','p'],['https://api.piped.yt','p'],['https://yewtu.be','i'],['https://yt.artemislena.eu','i'],['https://inv.tux.pizza','i']] as const;for(const[p,k]of ps){try{const url=k==='p'?`${p}/search?q=${encodeURIComponent(q)}&filter=videos`:`${p}/api/v1/search?q=${encodeURIComponent(q)}&type=video&page=1&region=IN`;const r=await fetch(url,{signal:AbortSignal.timeout(7000)});if(!r.ok)continue;const d=await r.json();const a=k==='p'?(Array.isArray(d?.items)?d.items:[]):(Array.isArray(d)?d:[]);const out=a.filter((x:any)=>k==='p'?x?.type==='stream'&&x?.id:x?.type==='video'&&x?.videoId).slice(0,20).map((x:any)=>{const id=k==='p'?x.id:x.videoId;const th=x.videoThumbnails||[];return{id,title:x.title||'YouTube Video',channel:k==='p'?(x.uploaderName||'YouTube'):(x.author||'YouTube'),views:x.viewCount?`${x.viewCount} views`:x.views?`${x.views} views`:'',publishedAt:x.publishedText||x.uploadedDate||'',duration:x.lengthSeconds?`${Math.floor(x.lengthSeconds/60)}:${String(x.lengthSeconds%60).padStart(2,'0')}`:x.duration||'',thumbnail:k==='i'?(th[th.length-1]?.url||`https://i.ytimg.com/vi/${id}/hqdefault.jpg`):(x.thumbnail||`https://i.ytimg.com/vi/${id}/hqdefault.jpg`),url:`https://www.youtube.com/watch?v=${id}`,videoUrl:`https://www.youtube.com/watch?v=${id}`}});if(out.length)return out}catch{}}return[]}
 static async getYouTubeSearch(q:string){if(!q.trim())return[];try{const r=await fetch(`/api/youtube/search?q=${encodeURIComponent(q.trim())}`,{signal:AbortSignal.timeout(7000)});const d=await r.json();if(Array.isArray(d.results)&&d.results.length)return d.results}catch{}return this.getYouTubeSearchFromPublicApi(q)}
 static async getYouTubeFeed(c='all'){try{const d=await(await fetch(`/api/youtube/feed?category=${encodeURIComponent(c)}`)).json();return d.results||[]}catch{return[]}}
 static async checkFrameEmbeddable(url:string){try{return await(await fetch(`/api/browser/frame-check?url=${encodeURIComponent(url)}`)).json()}catch{return{embeddable:false}}}
}
