import { MediaMetadata, FormatsResponse, DownloadProgressInfo, DownloadStatus } from '../types';
export interface InitDownloadParams{formatId:string;fileName?:string;customTitle?:string;url?:string;mediaId?:string;durationSeconds?:number;thumbnail?:string;type?:string;previewUrl?:string}
export interface InitDownloadResponse{success:boolean;downloadId:string;fileName:string;ext:string;formatLabel:string;mediaType:'video'|'audio'|'image';totalBytes:number;fileSizeStr:string;contentType:string;fileUrl:string;progressUrl:string}
export class ApiService{
static async getMetadata(url:string):Promise<MediaMetadata>{const r=await fetch('/api/metadata',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Unable to read media.');return d.data}
static async getFormats(durationSeconds=180,qualities:string[]=[],url?:string):Promise<FormatsResponse>{const r=await fetch('/api/formats',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({durationSeconds,qualities,url})});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Failed to retrieve formats.');return{audioFormats:d.audioFormats||[],videoFormats:d.videoFormats||[],imageFormats:d.imageFormats||[]}}
static async initDownload(p:InitDownloadParams):Promise<InitDownloadResponse>{const r=await fetch('/api/download',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json();if(!r.ok||!d.success)throw new Error(d.message||'Download failed.');return d}
static async getProgress(id:string):Promise<DownloadProgressInfo>{const d=await(await fetch(`/api/download/${encodeURIComponent(id)}/progress`)).json();if(!d.success)throw new Error(d.message||'Progress unavailable.');return{downloadId:d.downloadId,status:d.status,percent:d.percent,downloadedBytes:d.downloadedBytes,totalBytes:d.totalBytes,speed:d.speed,fileName:d.fileName,formatLabel:d.formatLabel,ext:d.ext,type:d.mediaType,thumbnail:d.thumbnail,errorMessage:d.errorMessage}}
static async cancelDownload(id:string){try{return(await fetch(`/api/download/${encodeURIComponent(id)}/cancel`,{method:'POST'})).ok}catch{return false}}
static async getYouTubeSuggestions(q:string){try{return(await(await fetch(`/api/youtube/suggestions?q=${encodeURIComponent(q)}`)).json()).suggestions||[]}catch{return[]}}
static async getYouTubeSearchFromPublicApi(q:string):Promise<any[]>{const ps=[['https://pipedapi.kavin.rocks','p'],['https://pipedapi.leptons.xyz','p'],['https://pipedapi.nosebs.ru','p'],['https://pipedapi.adminforge.de','p'],['https://api.piped.yt','p'],['https://yewtu.be','i'],['https://yt.artemislena.eu','i'],['https://inv.tux.pizza','i']] as const;for(const[p,k]of ps){try{const u=k==='p'?`${p}/search?q=${encodeURIComponent(q)}&filter=videos`:`${p}/api/v1/search?q=${encodeURIComponent(q)}&type=video&page=1&region=IN`;const r=await fetch(u,{signal:AbortSignal.timeout(6000)});if(!r.ok)continue;const d=await r.json();const a=k==='p'?(Array.isArray(d?.items)?d.items:[]):(Array.isArray(d)?d:[]);const out=a.filter((x:any)=>k==='p'?x?.type==='stream'&&x?.id:x?.type==='video'&&x?.videoId).slice(0,20).map((x:any)=>{const id=k==='p'?x.id:x.videoId,th=x.videoThumbnails||[];return{id,title:x.title||'YouTube Video',channel:k==='p'?(x.uploaderName||'YouTube'):(x.author||'YouTube'),views:x.viewCount?`${x.viewCount} views`:'',publishedAt:x.publishedText||x.uploadedDate||'',duration:x.lengthSeconds?`${Math.floor(x.lengthSeconds/60)}:${String(x.lengthSeconds%60).padStart(2,'0')}`:x.duration||'',thumbnail:k==='i'?(th[th.length-1]?.url||`https://i.ytimg.com/vi/${id}/hqdefault.jpg`):(x.thumbnail||`https://i.ytimg.com/vi/${id}/hqdefault.jpg`),url:`https://www.youtube.com/watch?v=${id}`}});if(out.length)return out}catch{}}return[]}
static async getYouTubeSearch(q:string){if(!q.trim())return[];try{const d=await(await fetch(`/api/youtube/search?q=${encodeURIComponent(q.trim())}`,{signal:AbortSignal.timeout(6000)})).json();if(Array.isArray(d.results)&&d.results.length)return d.results}catch{}return this.getYouTubeSearchFromPublicApi(q)}
static async getYouTubeFeed(c='all'){try{return(await(await fetch(`/api/youtube/feed?category=${encodeURIComponent(c)}`)).json()).results||[]}catch{return[]}}
static async checkFrameEmbeddable(url:string){try{return await(await fetch(`/api/browser/frame-check?url=${encodeURIComponent(url)}`)).json()}catch{return{embeddable:false}}}
}
